export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SET_RESIDENT_LIST = 'SET_RESIDENT_LIST';
export const SET_RESIDENT_FILTER = 'SET_RESIDENT_FILTER';
