const programInfo = {
  programName: "UNDERGRADUATE",
  infoCardsVisible: false,
  examScoresVisible: false,
  narrativesVisible: false,
  rotationList: [
    "Anesthesia",
    "Emergency Medicine",
    "Elective (Year 3)",
    "Elective (Year 4)",
    "Family Medicine",
    "Internal Medicine",
    "Longitudinal Integrated Clerkship",
    "Obs/Gyn",
    "Pediatrics",
    "Psychiatry",
    "Selective",
    "Surgery",
    "Other",
  ],
  rotationRequired: {
    "Emergency Medicine": 12,
    Anesthesia: 12,
    "Family Medicine": 12,
    Surgery: 12,
    "Internal Medicine": 12,
    "OBS/GYN": 12,
    Pediatrics: 12,
    Psychiatry: 12,
    "Elective (Year 3)": 12,
    "Elective (Year 4)": 12,
    Selective: 12,
    Other: 12,
    "Longitudinal Integrated Clerkship": 12,
  },
  epaSourceMap: {
    subRoot: {
      1: "Obtain a history and perform a physical examination adapted to the patient’s clinical situation",
      2: "Formulate and justify a prioritized differential diagnosis",
      3: "Formulate an initial plan of investigation based on the diagnostic hypotheses",
      4: "Interpret and communicate results of common diagnostic and screening tests",
      5: "Formulate, communicate and implement management plans",
      6: "Present oral and written reports that document a clinical encounter",
      7: "Provide and receive the handover in transitions of care",
      8: "Recognize a patient requiring urgent or emergent care, provide initial management and seek help",
      9: "Communicate in difficult situations",
      10: "Participate in health quality improvement initiatives",
      11: "Perform general procedures of a physician",
      12: "Educate patients on disease management, health promotion and preventive medicine",
      13: "Collaborate effectively with allied health professionals on the interdisciplinary care of a patient",
    },
    maxObservation: {
      1: 20,
      2: 20,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
      7: 20,
      8: 20,
      9: 20,
      10: 20,
      11: 20,
      12: 20,
      13: 20,
    },
  },
};

module.exports = programInfo;
